package weatherServer

const val OPEN_WEATHER_MAP_PATH = "https://api.openweathermap.org/data/2.5"
const val OPEN_WEATHER_MAP_API_KEY = "&appid=ece86214d27a8d2c3a6f208489f5b390"
//const val OPEN_WEATHER_MAP_CURRENT_REQUEST_TYPE = "/weather?"
const val OPEN_WEATHER_MAP_CURRENT_REQUEST_TYPE = "/onecall?"
const val OPEN_WEATHER_MAP_HOURLY_REQUEST_TYPE = "/onecall?"
const val OPEN_WEATHER_MAP_HOURLY_REQUEST_TYPE_ = "/forecast/hourly?"
const val OPEN_WEATHER_MAP_DAILY_REQUEST_TYPE = "/onecall?"
const val OPEN_WEATHER_MAP_DAILY_REQUEST_TYPE_ = "climate/month?"

const val WEATHERBIT_PATH = "http://api.weatherbit.io/v2.0"
const val WEATHERBIT_API_KEY = "&key=286754432c094a92a43d63c8d5161910"
const val WEATHERBIT_CURRENT_REQUEST_TYPE = "/current?"
const val WEATHERBIT_HOURLY_REQUEST_TYPE = "/forecast/hourly?"
const val WEATHERBIT_DAILY_REQUEST_TYPE = "/forecast/daily?"

const val REQUEST_PARAM_BY_LOCATION = "bylocation"
const val REQUEST_PARAM_BY_CITY_NAME = "bycityname"

const val LATITUDE_KEY: String = "latitude"
const val LONGITUDE_KEY: String = "longitude"
const val CITY_NAME_KEY: String = "city"
const val REQUEST_TYPE_KEY: String = "type"

const val REQUEST_TYPE_VALUE_CURRENT: String = "current"
const val REQUEST_TYPE_VALUE_HOURLY: String = "hourly"
const val REQUEST_TYPE_VALUE_DAILY: String = "daily"

const val PARSER_KEY_MAIN: String = "main"
const val PARSER_KEY_DATA: String = "data"
const val PARSER_KEY_LIST: String = "list"
const val PARSER_KEY_WEATHER: String = "weather"
const val PARSER_KEY_CODE: String = "code"
const val PARSER_KEY_DESCRIPTION: String = "description"
const val PARSER_KEY_POD: String = "pod"
const val PARSER_KEY_DT: String = "dt"
const val PARSER_KEY_TS: String = "ts"
const val PARSER_KEY_DATE: String = "date"
const val PARSER_KEY_TEMP: String = "temp"
const val PARSER_KEY_MAX_TEMP: String = "max_temp"
const val PARSER_KEY_MIN_TEMP: String = "min_temp"
const val PARSER_KEY_APP_MAX_TEMP: String = "app_max_temp"
const val PARSER_KEY_FEEL_LIKE_MAX_TEMP: String = "feel_like_max_temp"
const val PARSER_KEY_FEEL_LIKE_MIX_TEMP: String = "feel_like_app_max_temp"
const val PARSER_KEY_APP_MIN_TEMP: String = "app_min_temp"
const val PARSER_KEY_FEEL_LIKE: String = "feel_like"
const val PARSER_KEY_FEELS_LIKE: String = "feels_like"
const val PARSER_KEY_APP_TEMP: String = "app_temp"
const val PARSER_KEY_PRESSURE: String = "pressure"
const val PARSER_KEY_PRES: String = "pres"
const val PARSER_KEY_HUMIDITY: String = "humidity"
const val PARSER_KEY_RH: String = "rh"
const val PARSER_KEY_WIND_SPEED: String = "wind_speed"
const val PARSER_KEY_WIND_SPD: String = "wind_spd"
const val PARSER_KEY_WIND: String = "wind"
const val PARSER_KEY_SPEED: String = "speed"
const val PARSER_KEY_WIND_DEG: String = "wind_deg"
const val PARSER_KEY_WIND_DIR: String = "wind_dir"
const val PARSER_KEY_WIND_CDIR_FULL: String = "wind_cdir_full"
const val PARSER_KEY_POP: String = "pop"
const val PARSER_KEY_UV: String = "uv"
const val PARSER_KEY_UVI: String = "uvi"
const val PARSER_KEY_UV_INDEX: String = "uv_index"
const val PARSER_KEY_VIS: String = "vis"
const val PARSER_KEY_VISIBILITY: String = "visibility"
const val PARSER_KEY_DEWPT: String = "dewpt"
const val PARSER_KEY_DEW_POINT: String = "dew_point"
const val PARSER_KEY_CURRENT: String = "current"
const val PARSER_KEY_HOURLY: String = "hourly"
const val PARSER_KEY_DAILY: String = "daily"
const val PARSER_KEY_DAY: String = "day"
const val PARSER_KEY_NIGHT: String = "night"
const val PARSER_KEY_ID: String = "id"
const val PARSER_KEY_MAX: String = "max"
const val PARSER_KEY_MIN: String = "min"